name: Displaychest
version: '${project.version}'
main: me.xingyan.displaychest.Main
api-version: 1.18
commands:
  displaychest:
    usage: /<command>
    aliases:
      - dc
    permission: displaychest.use